version: '3'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 8081:80
   - 444:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - app

  app:
    restart: always
    build: .
    working_dir: /app
    volumes:
      - .:/app
    expose:
      - "8080"
    command: mvn clean spring-boot:run
