apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ingress-test.fullname" . }}
  labels:
    app: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: {{ template "ingress-test.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
            path: /
            pathType: Prefix